image: themattrix/tox

stages:
  - static_check

before_script:
  - pyenv global $(pyenv global | grep "^3.5")  # Set Python 3.5 as default.
  - pip install -r requirements_dev.txt

static_check:
  stage: static_check
  script:
    - flake8 .
